version: "3.7"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    # command: gunicorn django_postgres_api.wsgi:application --bind 0.0.0.0:8000
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
